# Generated by Django 6.1 on 2026-08-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.SmallIntegerField(choices=[(1, 'usd'), (2, 'eur')], default=1, max_length=3, verbose_name='валюта'),
        ),
    ]
